#!/bin/bash

############################################
## EXPECTS THAT JUDGEMENTS HAVE BEEN MADE ##
############################################
# where # is the topic number

echo "Getting RRF START!"

numoftopics=40

for i in {1..40}
do
	run1_results="run1_results_${i}"
	run2_results="run2_results_${i}"
	run3_results="run3_results_${i}"
	awk '{ print NR, $0 }' $run1_results | sort -k2 > t1
	awk '{ print NR, $0 }' $run2_results | sort -k2 > t2
	awk '{ print NR, $0 }' $run3_results | sort -k2 > t3
	
	join -1 2 -2 2 -a 1 -a 2 t1 t2 | sort -k1 > t12
	join -1 1 -2 2 -a 1 -a 2 t12 t3 > t123
	
	cut -d ' ' -f 1 t123 > temp
	awk '{ print (1/(60+$2))+(1/(60+$3))+(1/(60+$4)) }' t123 > rrfscores
	
	rrf_results="rrf_results_${i}"
	
	paste -d ' ' rrfscores temp | sort -rn | cut -d ' ' -f 2 | head -n 1000 > $rrf_results	
done

# parameter 1: runid (xj4wang_runX)
# parameter 2: number of topics (round3 = 40)
# parameter 3: topic names (e.g. run2_results)
python makeFinalDoc.py "xj4wang_rrf" $numoftopics "rrf_results"



echo "Getting RRF DONE!"