#!/bin/bash

#############################################
## EXPECTS THAT setup_do-once HAS BEEN RUN ##
#############################################
# where # is the topic number

echo "Verify top 10 START!"

topic=$1
working_files="WORKINGFILES"
directory="metadata_files"
starter_topic="${working_files}/starter_topic_$topic"
relevant_words_file="${working_files}/relevant_words_file_${topic}"
topb_rel="run1_results_${topic}"

touch $relevant_words_file
rm $relevant_words_file
head -n 20 $topb_rel > temp10
while read filename;
do
	#######################################
	## CHOOSING WORDS TO HIGHLIGHT start ##
	#######################################
	~/featurekit/porteroff "${directory}/$filename" | sort > list1
	cut -d ' ' -f 2 df | cat -n > list2
	join -1 1 -2 2 list1 list2 > list3

	cut -d ' ' -f 4 list3 > model_posns

	touch temp
	rm temp
	while read line;
	do
		cut -d ' ' -f $((line+1)) $model >> temp
	done < model_posns

	cut -d ' ' -f 1 list3 > temp2
	paste -d ' ' temp temp2 | uniq | sort -gr | grep -v "^0 " | grep -v "^-" | head -n 5 | cut -d ' ' -f 2 > temp3
	
	cat temp3 | awk -vORS=, '{ print $1 }' | sed 's/,$/\n/' >> $relevant_words_file # take top 5 according to Gordon

	rm list1
	rm list2
	rm list3
	rm temp
	rm temp2
	rm temp3

	#####################################
	## CHOOSING WORDS TO HIGHLIGHT end ##
	#####################################
done < temp10
rm temp10

echo "Starting human judgements!"
python displayMetadataFile_verify.py $topb_rel $topic $directory $relevant_words_file
echo "Finished human judgements!"

echo "Verify top 10 END!"
