#!/bin/bash

###########################################
## RUN getFinalResults for all 30 topics ##
###########################################
# where # is the topic number

echo "Getting Final Results RUN START!"

for i in {1..40}
do
	./getFinalResults $i
done

# parameter 1: runid (xj4wang_runX)
# parameter 2: number of topics (round3 = 40)
# parameter 3: topic names (e.g. run2_results)
python makeFinalDoc.py "xj4wang_run1" 40 "run1_results"
python makeFinalDoc.py "xj4wang_run2" 40 "run2_results"
python makeFinalDoc.py "xj4wang_run3" 40 "run3_results"

# REPEAT
echo "Getting Final Results RUN DONE!"