#!/bin/bash

#############################################
## EXPECTS THAT setup_do-once HAS BEEN RUN ##
#############################################
# where # is the topic number

echo "Judging AUTO files START!"

topic=$1
working_files="WORKINGFILES"
directory="metadata_files"
train_file="${working_files}/train_file_$topic"
test_file="${working_files}/test_file_$topic"
test_file_ids="${working_files}/test_file_ids_$topic"
model="${working_files}/model_$topic"
results="${working_files}/results_file_$topic" # this doesn't really matter, is never used
topN_rel="${working_files}/topN_rel"
qrel_file="qrels-rnd1.txt"
N=1 #number of files to judge before retraining the model
relevant_words_file="${working_files}/relevant_words_file_$topic"
jj_file="${working_files}/jj_topic_$topic"

# hyperparameters by https://dl.acm.org/doi/10.1145/2600428.2609601
iterations=2000000
dimensionality=1100000
learner_type="logreg-pegasos" #paper only says Pegasos, log-pegasos is chosen from Gordon's class
# hyperparameters by Gordon's class
loop_type="stochastic" #he didn't specify, we went with the one that's binary labeling
lambda=0.001

# filter out the ones that have been judged (using jj_topic_#) and label accordingly
# and store results to train_file, the rest are stored to test_file wtih rel 0
python label_rel.py $topic $train_file $test_file $test_file_ids $working_files

# feed training_file_# to sofiaML to and obtain the model
~/sofia-ml-read-only/sofia-ml --learner_type $learner_type --loop_type $loop_type --lambda $lambda --iterations $iterations --dimensionality $dimensionality --training_file $train_file --model_out $model

# feed model and testing_file_# to sofiaML to get rel judgements
~/sofia-ml-read-only/sofia-ml --model_in $model --test_file $test_file --results_file $results

# select the top 10 most rel documents from not_judged_files_#
# according to SofiaML
# paste together file ids and their results before sorting
cut -f 1 $results > t2
paste -d ' ' t2 $test_file_ids > t3
mv t3 $results

# sort results by rel, then by conf where k1 = conf, k2 = name
# show only the top 10 to be labeled
sort -rn $results | head -n $N | cut -d ' ' -f 2 > $topN_rel

# use qrel file to make the judgement instead of a human assessor
doc_to_judge=`cat $topN_rel`
grep "^$topic " $qrel_file | grep $doc_to_judge > t
count=`cat t | wc -l`
if [ $count -eq 1 ];
then
	cut -d ' ' -f 4 t > t2
	cut -d ' ' -f 5 t > t3
	paste -d ',' t2 t3 >> $jj_file
elif [ $count -eq 0 ];
then
	echo "${doc_to_judge},0" >> $jj_file
else
	echo 'ERROR!!!' >> OMG_ERROR_HELP
fi

# REPEAT
echo "Judging AUTO files DONE!"